/**
 * Copies the compiled ABIs the frontend needs out of Hardhat's artifacts and
 * into frontend/src/generated/abi.ts.
 *
 * The frontend imports the ABI from here rather than keeping its own copy, so
 * a contract change cannot silently drift from the UI calling it. Run via
 * `npm run gen`; the root build runs it between compile and the Next build.
 */
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const outFile = join(root, "frontend", "src", "generated", "abi.ts");

const CONTRACTS = [
  ["picasoTokenAbi", "contracts/PicasoToken.sol/PicasoToken.json"],
  ["erc20Abi", "contracts/mocks/MockERC20.sol/MockERC20.json"],
  // The UI quotes a redemption through the same conversionPath/rateByPath the
  // contract uses, so the figure it shows is the one liquidateNft will get.
  ["bancorNetworkAbi", "contracts/interfaces/IBancor.sol/IBancorNetwork.json"],
];

async function readAbi(artifactPath) {
  const full = join(root, "artifacts", artifactPath);
  try {
    return JSON.parse(await readFile(full, "utf8")).abi;
  } catch (error) {
    throw new Error(
      `Missing artifact ${artifactPath}. Run \`npm run compile\` first. (${error.message})`,
    );
  }
}

const banner = `// GENERATED by scripts/export-abi.mjs — do not edit.
// Refresh with \`npm run gen\` after changing a contract.
`;

const parts = await Promise.all(
  CONTRACTS.map(async ([name, path]) => {
    const abi = await readAbi(path);
    return `export const ${name} = ${JSON.stringify(abi, null, 2)} as const;\n`;
  }),
);

await mkdir(dirname(outFile), { recursive: true });
await writeFile(outFile, `${banner}\n${parts.join("\n")}`);

console.log(`Wrote ${outFile}`);
